import React from 'react'
import '@testing-library/jest-dom/extend-expect'
import { render, screen } from '@testing-library/react'
import Tracks from './Tracks'

test('renders content', () => {
  const tracks = {
    
        "href": "https://api.spotify.com/v1/search?query=ma&type=track&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=0&limit=4",
        "items": [
            {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/4obzFoKoKRHIphyHzJ35G3"
                            },
                            "href": "https://api.spotify.com/v1/artists/4obzFoKoKRHIphyHzJ35G3",
                            "id": "4obzFoKoKRHIphyHzJ35G3",
                            "name": "Becky G",
                            "type": "artist",
                            "uri": "spotify:artist:4obzFoKoKRHIphyHzJ35G3"
                        },
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/790FomKkXshlbRYZFtlgla"
                            },
                            "href": "https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla",
                            "id": "790FomKkXshlbRYZFtlgla",
                            "name": "KAROL G",
                            "type": "artist",
                            "uri": "spotify:artist:790FomKkXshlbRYZFtlgla"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6GHUywBU0u92lg0Dhrt40R"
                    },
                    "href": "https://api.spotify.com/v1/albums/6GHUywBU0u92lg0Dhrt40R",
                    "id": "6GHUywBU0u92lg0Dhrt40R",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b27372babf690675fe969470e8ee",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e0272babf690675fe969470e8ee",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d0000485172babf690675fe969470e8ee",
                            "width": 64
                        }
                    ],
                    "name": "MAMIII",
                    "release_date": "2022-02-10",
                    "release_date_precision": "day",
                    "total_tracks": 1,
                    "type": "album",
                    "uri": "spotify:album:6GHUywBU0u92lg0Dhrt40R"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4obzFoKoKRHIphyHzJ35G3"
                        },
                        "href": "https://api.spotify.com/v1/artists/4obzFoKoKRHIphyHzJ35G3",
                        "id": "4obzFoKoKRHIphyHzJ35G3",
                        "name": "Becky G",
                        "type": "artist",
                        "uri": "spotify:artist:4obzFoKoKRHIphyHzJ35G3"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/790FomKkXshlbRYZFtlgla"
                        },
                        "href": "https://api.spotify.com/v1/artists/790FomKkXshlbRYZFtlgla",
                        "id": "790FomKkXshlbRYZFtlgla",
                        "name": "KAROL G",
                        "type": "artist",
                        "uri": "spotify:artist:790FomKkXshlbRYZFtlgla"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AG",
                    "AL",
                    "AM",
                    "AO",
                    "AR",
                    "AT",
                    "AU",
                    "AZ",
                    "BA",
                    "BB",
                    "BD",
                    "BE",
                    "BF",
                    "BG",
                    "BH",
                    "BI",
                    "BJ",
                    "BN",
                    "BO",
                    "BR",
                    "BS",
                    "BT",
                    "BW",
                    "BY",
                    "BZ",
                    "CA",
                    "CD",
                    "CG",
                    "CH",
                    "CI",
                    "CL",
                    "CM",
                    "CO",
                    "CR",
                    "CV",
                    "CW",
                    "CY",
                    "CZ",
                    "DE",
                    "DJ",
                    "DK",
                    "DM",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FJ",
                    "FM",
                    "FR",
                    "GA",
                    "GB",
                    "GD",
                    "GE",
                    "GH",
                    "GM",
                    "GN",
                    "GQ",
                    "GR",
                    "GT",
                    "GW",
                    "GY",
                    "HK",
                    "HN",
                    "HR",
                    "HT",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IQ",
                    "IS",
                    "IT",
                    "JM",
                    "JO",
                    "JP",
                    "KE",
                    "KG",
                    "KH",
                    "KI",
                    "KM",
                    "KN",
                    "KR",
                    "KW",
                    "KZ",
                    "LA",
                    "LB",
                    "LC",
                    "LI",
                    "LK",
                    "LR",
                    "LS",
                    "LT",
                    "LU",
                    "LV",
                    "LY",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MG",
                    "MH",
                    "MK",
                    "ML",
                    "MN",
                    "MO",
                    "MR",
                    "MT",
                    "MU",
                    "MV",
                    "MW",
                    "MX",
                    "MY",
                    "MZ",
                    "NA",
                    "NE",
                    "NG",
                    "NI",
                    "NL",
                    "NO",
                    "NP",
                    "NR",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PG",
                    "PH",
                    "PK",
                    "PL",
                    "PS",
                    "PT",
                    "PW",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "RW",
                    "SA",
                    "SB",
                    "SC",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SL",
                    "SM",
                    "SN",
                    "SR",
                    "ST",
                    "SV",
                    "SZ",
                    "TD",
                    "TG",
                    "TH",
                    "TJ",
                    "TL",
                    "TN",
                    "TO",
                    "TR",
                    "TT",
                    "TV",
                    "TW",
                    "TZ",
                    "UA",
                    "UG",
                    "US",
                    "UY",
                    "UZ",
                    "VC",
                    "VE",
                    "VN",
                    "VU",
                    "WS",
                    "XK",
                    "ZA",
                    "ZM",
                    "ZW"
                ],
                "disc_number": 1,
                "duration_ms": 226088,
                "explicit": false,
                "external_ids": {
                    "isrc": "USRC12200425"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/1ri9ZUkBJVFUdgwzCnfcYs"
                },
                "href": "https://api.spotify.com/v1/tracks/1ri9ZUkBJVFUdgwzCnfcYs",
                "id": "1ri9ZUkBJVFUdgwzCnfcYs",
                "is_local": false,
                "name": "MAMIII",
                "popularity": 98,
                "preview_url": "https://p.scdn.co/mp3-preview/a2748f563c888258e379756cdc94922b9c7c9cde?cid=0d78c774b6eb44a8bc04de3f77f8e46c",
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:1ri9ZUkBJVFUdgwzCnfcYs"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/2CCgb0KApjfQDuTppovpf8"
                            },
                            "href": "https://api.spotify.com/v1/artists/2CCgb0KApjfQDuTppovpf8",
                            "id": "2CCgb0KApjfQDuTppovpf8",
                            "name": "Rvfv",
                            "type": "artist",
                            "uri": "spotify:artist:2CCgb0KApjfQDuTppovpf8"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6wl31M47YdcV6eNyfXCjCk"
                    },
                    "href": "https://api.spotify.com/v1/albums/6wl31M47YdcV6eNyfXCjCk",
                    "id": "6wl31M47YdcV6eNyfXCjCk",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b273ea13f28450e095021d2bcbfe",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e02ea13f28450e095021d2bcbfe",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d00004851ea13f28450e095021d2bcbfe",
                            "width": 64
                        }
                    ],
                    "name": "NASTU",
                    "release_date": "2022-01-28",
                    "release_date_precision": "day",
                    "total_tracks": 15,
                    "type": "album",
                    "uri": "spotify:album:6wl31M47YdcV6eNyfXCjCk"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2CCgb0KApjfQDuTppovpf8"
                        },
                        "href": "https://api.spotify.com/v1/artists/2CCgb0KApjfQDuTppovpf8",
                        "id": "2CCgb0KApjfQDuTppovpf8",
                        "name": "Rvfv",
                        "type": "artist",
                        "uri": "spotify:artist:2CCgb0KApjfQDuTppovpf8"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2f6TzIGIIxEuwp6o7kEbhy"
                        },
                        "href": "https://api.spotify.com/v1/artists/2f6TzIGIIxEuwp6o7kEbhy",
                        "id": "2f6TzIGIIxEuwp6o7kEbhy",
                        "name": "Pablo Mas",
                        "type": "artist",
                        "uri": "spotify:artist:2f6TzIGIIxEuwp6o7kEbhy"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AG",
                    "AL",
                    "AM",
                    "AO",
                    "AR",
                    "AT",
                    "AU",
                    "AZ",
                    "BA",
                    "BB",
                    "BD",
                    "BE",
                    "BF",
                    "BG",
                    "BH",
                    "BI",
                    "BJ",
                    "BN",
                    "BO",
                    "BR",
                    "BS",
                    "BT",
                    "BW",
                    "BY",
                    "BZ",
                    "CA",
                    "CD",
                    "CG",
                    "CH",
                    "CI",
                    "CL",
                    "CM",
                    "CO",
                    "CR",
                    "CV",
                    "CW",
                    "CY",
                    "CZ",
                    "DE",
                    "DJ",
                    "DK",
                    "DM",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FJ",
                    "FM",
                    "FR",
                    "GA",
                    "GB",
                    "GD",
                    "GE",
                    "GH",
                    "GM",
                    "GN",
                    "GQ",
                    "GR",
                    "GT",
                    "GW",
                    "GY",
                    "HK",
                    "HN",
                    "HR",
                    "HT",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IQ",
                    "IS",
                    "IT",
                    "JM",
                    "JO",
                    "JP",
                    "KE",
                    "KG",
                    "KH",
                    "KI",
                    "KM",
                    "KN",
                    "KR",
                    "KW",
                    "KZ",
                    "LA",
                    "LB",
                    "LC",
                    "LI",
                    "LK",
                    "LR",
                    "LS",
                    "LT",
                    "LU",
                    "LV",
                    "LY",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MG",
                    "MH",
                    "MK",
                    "ML",
                    "MN",
                    "MO",
                    "MR",
                    "MT",
                    "MU",
                    "MV",
                    "MW",
                    "MX",
                    "MY",
                    "MZ",
                    "NA",
                    "NE",
                    "NG",
                    "NI",
                    "NL",
                    "NO",
                    "NP",
                    "NR",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PG",
                    "PH",
                    "PK",
                    "PL",
                    "PS",
                    "PT",
                    "PW",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "RW",
                    "SA",
                    "SB",
                    "SC",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SL",
                    "SM",
                    "SN",
                    "SR",
                    "ST",
                    "SV",
                    "SZ",
                    "TD",
                    "TG",
                    "TH",
                    "TJ",
                    "TL",
                    "TN",
                    "TO",
                    "TR",
                    "TT",
                    "TV",
                    "TW",
                    "TZ",
                    "UA",
                    "UG",
                    "US",
                    "UY",
                    "UZ",
                    "VC",
                    "VE",
                    "VN",
                    "VU",
                    "WS",
                    "XK",
                    "ZA",
                    "ZM",
                    "ZW"
                ],
                "disc_number": 1,
                "duration_ms": 168367,
                "explicit": false,
                "external_ids": {
                    "isrc": "ES71G2201747"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4FjkjrvfbB3C4eUqWlw3vB"
                },
                "href": "https://api.spotify.com/v1/tracks/4FjkjrvfbB3C4eUqWlw3vB",
                "id": "4FjkjrvfbB3C4eUqWlw3vB",
                "is_local": false,
                "name": "Mami",
                "popularity": 77,
                "preview_url": "https://p.scdn.co/mp3-preview/21ebd12012c651f91107ac3fd1daad165ebedd29?cid=0d78c774b6eb44a8bc04de3f77f8e46c",
                "track_number": 3,
                "type": "track",
                "uri": "spotify:track:4FjkjrvfbB3C4eUqWlw3vB"
            },
            {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/7DOERbtkx9aTLvWzZSB0qx"
                            },
                            "href": "https://api.spotify.com/v1/artists/7DOERbtkx9aTLvWzZSB0qx",
                            "id": "7DOERbtkx9aTLvWzZSB0qx",
                            "name": "Rigoberta Bandini",
                            "type": "artist",
                            "uri": "spotify:artist:7DOERbtkx9aTLvWzZSB0qx"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CW",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/26As3PYmCCD390xoIJ4RE6"
                    },
                    "href": "https://api.spotify.com/v1/albums/26As3PYmCCD390xoIJ4RE6",
                    "id": "26As3PYmCCD390xoIJ4RE6",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b2735d5cbdd99bf56496673070b0",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e025d5cbdd99bf56496673070b0",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d000048515d5cbdd99bf56496673070b0",
                            "width": 64
                        }
                    ],
                    "name": "Ay Mamá",
                    "release_date": "2021-12-23",
                    "release_date_precision": "day",
                    "total_tracks": 1,
                    "type": "album",
                    "uri": "spotify:album:26As3PYmCCD390xoIJ4RE6"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/7DOERbtkx9aTLvWzZSB0qx"
                        },
                        "href": "https://api.spotify.com/v1/artists/7DOERbtkx9aTLvWzZSB0qx",
                        "id": "7DOERbtkx9aTLvWzZSB0qx",
                        "name": "Rigoberta Bandini",
                        "type": "artist",
                        "uri": "spotify:artist:7DOERbtkx9aTLvWzZSB0qx"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AG",
                    "AL",
                    "AM",
                    "AO",
                    "AR",
                    "AT",
                    "AU",
                    "AZ",
                    "BA",
                    "BB",
                    "BD",
                    "BE",
                    "BF",
                    "BG",
                    "BH",
                    "BI",
                    "BJ",
                    "BN",
                    "BO",
                    "BR",
                    "BS",
                    "BT",
                    "BW",
                    "BY",
                    "BZ",
                    "CA",
                    "CD",
                    "CG",
                    "CH",
                    "CI",
                    "CL",
                    "CM",
                    "CO",
                    "CR",
                    "CV",
                    "CW",
                    "CY",
                    "CZ",
                    "DE",
                    "DJ",
                    "DK",
                    "DM",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FJ",
                    "FM",
                    "FR",
                    "GA",
                    "GB",
                    "GD",
                    "GE",
                    "GH",
                    "GM",
                    "GN",
                    "GQ",
                    "GR",
                    "GT",
                    "GW",
                    "GY",
                    "HK",
                    "HN",
                    "HR",
                    "HT",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IQ",
                    "IS",
                    "IT",
                    "JM",
                    "JO",
                    "JP",
                    "KE",
                    "KG",
                    "KH",
                    "KI",
                    "KM",
                    "KN",
                    "KR",
                    "KW",
                    "KZ",
                    "LA",
                    "LB",
                    "LC",
                    "LI",
                    "LK",
                    "LR",
                    "LS",
                    "LT",
                    "LU",
                    "LV",
                    "LY",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MG",
                    "MH",
                    "MK",
                    "ML",
                    "MN",
                    "MO",
                    "MR",
                    "MT",
                    "MU",
                    "MV",
                    "MW",
                    "MX",
                    "MY",
                    "MZ",
                    "NA",
                    "NE",
                    "NG",
                    "NI",
                    "NL",
                    "NO",
                    "NP",
                    "NR",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PG",
                    "PH",
                    "PK",
                    "PL",
                    "PS",
                    "PT",
                    "PW",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "RW",
                    "SA",
                    "SB",
                    "SC",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SL",
                    "SM",
                    "SN",
                    "SR",
                    "ST",
                    "SV",
                    "SZ",
                    "TD",
                    "TG",
                    "TH",
                    "TJ",
                    "TL",
                    "TN",
                    "TO",
                    "TR",
                    "TT",
                    "TV",
                    "TW",
                    "TZ",
                    "UA",
                    "UG",
                    "US",
                    "UY",
                    "UZ",
                    "VC",
                    "VE",
                    "VN",
                    "VU",
                    "WS",
                    "XK",
                    "ZA",
                    "ZM",
                    "ZW"
                ],
                "disc_number": 1,
                "duration_ms": 181695,
                "explicit": false,
                "external_ids": {
                    "isrc": "QMFMF2131022"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/0khVEzctbwmqLvOpg1ecbg"
                },
                "href": "https://api.spotify.com/v1/tracks/0khVEzctbwmqLvOpg1ecbg",
                "id": "0khVEzctbwmqLvOpg1ecbg",
                "is_local": false,
                "name": "Ay Mamá",
                "popularity": 78,
                "preview_url": "https://p.scdn.co/mp3-preview/3e82dcf2090785205acc21e51b81b42a09ed7b58?cid=0d78c774b6eb44a8bc04de3f77f8e46c",
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:0khVEzctbwmqLvOpg1ecbg"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/1bAftSH8umNcGZ0uyV7LMg"
                            },
                            "href": "https://api.spotify.com/v1/artists/1bAftSH8umNcGZ0uyV7LMg",
                            "id": "1bAftSH8umNcGZ0uyV7LMg",
                            "name": "Duki",
                            "type": "artist",
                            "uri": "spotify:artist:1bAftSH8umNcGZ0uyV7LMg"
                        }
                    ],
                    "available_markets": [
                        "AD",
                        "AE",
                        "AG",
                        "AL",
                        "AM",
                        "AO",
                        "AR",
                        "AT",
                        "AU",
                        "AZ",
                        "BA",
                        "BB",
                        "BD",
                        "BE",
                        "BF",
                        "BG",
                        "BH",
                        "BI",
                        "BJ",
                        "BN",
                        "BO",
                        "BR",
                        "BS",
                        "BT",
                        "BW",
                        "BY",
                        "BZ",
                        "CA",
                        "CD",
                        "CG",
                        "CH",
                        "CI",
                        "CL",
                        "CM",
                        "CO",
                        "CR",
                        "CV",
                        "CY",
                        "CZ",
                        "DE",
                        "DJ",
                        "DK",
                        "DM",
                        "DO",
                        "DZ",
                        "EC",
                        "EE",
                        "EG",
                        "ES",
                        "FI",
                        "FJ",
                        "FM",
                        "FR",
                        "GA",
                        "GB",
                        "GD",
                        "GE",
                        "GH",
                        "GM",
                        "GN",
                        "GQ",
                        "GR",
                        "GT",
                        "GW",
                        "GY",
                        "HK",
                        "HN",
                        "HR",
                        "HT",
                        "HU",
                        "ID",
                        "IE",
                        "IL",
                        "IN",
                        "IQ",
                        "IS",
                        "IT",
                        "JM",
                        "JO",
                        "JP",
                        "KE",
                        "KG",
                        "KH",
                        "KI",
                        "KM",
                        "KN",
                        "KR",
                        "KW",
                        "KZ",
                        "LA",
                        "LB",
                        "LC",
                        "LI",
                        "LK",
                        "LR",
                        "LS",
                        "LT",
                        "LU",
                        "LV",
                        "LY",
                        "MA",
                        "MC",
                        "MD",
                        "ME",
                        "MG",
                        "MH",
                        "MK",
                        "ML",
                        "MN",
                        "MO",
                        "MR",
                        "MT",
                        "MU",
                        "MV",
                        "MW",
                        "MX",
                        "MY",
                        "MZ",
                        "NA",
                        "NE",
                        "NG",
                        "NI",
                        "NL",
                        "NO",
                        "NP",
                        "NR",
                        "NZ",
                        "OM",
                        "PA",
                        "PE",
                        "PG",
                        "PH",
                        "PK",
                        "PL",
                        "PS",
                        "PT",
                        "PW",
                        "PY",
                        "QA",
                        "RO",
                        "RS",
                        "RU",
                        "RW",
                        "SA",
                        "SB",
                        "SC",
                        "SE",
                        "SG",
                        "SI",
                        "SK",
                        "SL",
                        "SM",
                        "SN",
                        "SR",
                        "ST",
                        "SV",
                        "SZ",
                        "TD",
                        "TG",
                        "TH",
                        "TJ",
                        "TL",
                        "TN",
                        "TO",
                        "TR",
                        "TT",
                        "TV",
                        "TW",
                        "TZ",
                        "UA",
                        "UG",
                        "US",
                        "UY",
                        "UZ",
                        "VC",
                        "VE",
                        "VN",
                        "VU",
                        "WS",
                        "XK",
                        "ZA",
                        "ZM",
                        "ZW"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/3MKQjYpaES80tFP7Qo2zH0"
                    },
                    "href": "https://api.spotify.com/v1/albums/3MKQjYpaES80tFP7Qo2zH0",
                    "id": "3MKQjYpaES80tFP7Qo2zH0",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b273305240b65c28020de3aac8eb",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e02305240b65c28020de3aac8eb",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d00004851305240b65c28020de3aac8eb",
                            "width": 64
                        }
                    ],
                    "name": "Desde el Fin del Mundo",
                    "release_date": "2021-04-22",
                    "release_date_precision": "day",
                    "total_tracks": 18,
                    "type": "album",
                    "uri": "spotify:album:3MKQjYpaES80tFP7Qo2zH0"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/1bAftSH8umNcGZ0uyV7LMg"
                        },
                        "href": "https://api.spotify.com/v1/artists/1bAftSH8umNcGZ0uyV7LMg",
                        "id": "1bAftSH8umNcGZ0uyV7LMg",
                        "name": "Duki",
                        "type": "artist",
                        "uri": "spotify:artist:1bAftSH8umNcGZ0uyV7LMg"
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/716NhGYqD1jl2wI1Qkgq36"
                        },
                        "href": "https://api.spotify.com/v1/artists/716NhGYqD1jl2wI1Qkgq36",
                        "id": "716NhGYqD1jl2wI1Qkgq36",
                        "name": "Bizarrap",
                        "type": "artist",
                        "uri": "spotify:artist:716NhGYqD1jl2wI1Qkgq36"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AG",
                    "AL",
                    "AM",
                    "AO",
                    "AR",
                    "AT",
                    "AU",
                    "AZ",
                    "BA",
                    "BB",
                    "BD",
                    "BE",
                    "BF",
                    "BG",
                    "BH",
                    "BI",
                    "BJ",
                    "BN",
                    "BO",
                    "BR",
                    "BS",
                    "BT",
                    "BW",
                    "BY",
                    "BZ",
                    "CA",
                    "CD",
                    "CG",
                    "CH",
                    "CI",
                    "CL",
                    "CM",
                    "CO",
                    "CR",
                    "CV",
                    "CY",
                    "CZ",
                    "DE",
                    "DJ",
                    "DK",
                    "DM",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FJ",
                    "FM",
                    "FR",
                    "GA",
                    "GB",
                    "GD",
                    "GE",
                    "GH",
                    "GM",
                    "GN",
                    "GQ",
                    "GR",
                    "GT",
                    "GW",
                    "GY",
                    "HK",
                    "HN",
                    "HR",
                    "HT",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IQ",
                    "IS",
                    "IT",
                    "JM",
                    "JO",
                    "JP",
                    "KE",
                    "KG",
                    "KH",
                    "KI",
                    "KM",
                    "KN",
                    "KR",
                    "KW",
                    "KZ",
                    "LA",
                    "LB",
                    "LC",
                    "LI",
                    "LK",
                    "LR",
                    "LS",
                    "LT",
                    "LU",
                    "LV",
                    "LY",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MG",
                    "MH",
                    "MK",
                    "ML",
                    "MN",
                    "MO",
                    "MR",
                    "MT",
                    "MU",
                    "MV",
                    "MW",
                    "MX",
                    "MY",
                    "MZ",
                    "NA",
                    "NE",
                    "NG",
                    "NI",
                    "NL",
                    "NO",
                    "NP",
                    "NR",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PG",
                    "PH",
                    "PK",
                    "PL",
                    "PS",
                    "PT",
                    "PW",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "RW",
                    "SA",
                    "SB",
                    "SC",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SL",
                    "SM",
                    "SN",
                    "SR",
                    "ST",
                    "SV",
                    "SZ",
                    "TD",
                    "TG",
                    "TH",
                    "TJ",
                    "TL",
                    "TN",
                    "TO",
                    "TR",
                    "TT",
                    "TV",
                    "TW",
                    "TZ",
                    "UA",
                    "UG",
                    "US",
                    "UY",
                    "UZ",
                    "VC",
                    "VE",
                    "VN",
                    "VU",
                    "WS",
                    "XK",
                    "ZA",
                    "ZM",
                    "ZW"
                ],
                "disc_number": 1,
                "duration_ms": 175890,
                "explicit": true,
                "external_ids": {
                    "isrc": "AREZZ2100010"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/6KEb17S00Inf0v1qYDgUAj"
                },
                "href": "https://api.spotify.com/v1/tracks/6KEb17S00Inf0v1qYDgUAj",
                "id": "6KEb17S00Inf0v1qYDgUAj",
                "is_local": false,
                "name": "Malbec",
                "popularity": 76,
                "preview_url": "https://p.scdn.co/mp3-preview/3a8a070801aff6e54d3c49b8b3d710c6b83c6ea3?cid=0d78c774b6eb44a8bc04de3f77f8e46c",
                "track_number": 10,
                "type": "track",
                "uri": "spotify:track:6KEb17S00Inf0v1qYDgUAj"
            }
        ],
        "limit": 4,
        "next": "https://api.spotify.com/v1/search?query=ma&type=track&locale=en-GB%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8&offset=4&limit=4",
        "offset": 0,
        "previous": null,
        "total": 10125
    }

  render(<Tracks tracks={tracks} />)

  const title = screen.getByText('Songs')
  const element = screen.getByText('Malbec')
  const element2 = screen.getByText('Desde el Fin del Mundo')
  
  expect(title).toBeDefined()
  expect(element).toBeDefined()
  expect(element).toHaveAttribute('href', 'spotify:track:6KEb17S00Inf0v1qYDgUAj')
  expect(element2).toBeDefined()
})